name: Lint and Format
on:
  push:
    branches:
      - 'main'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff (lint)
      run: ruff check --output-format=github .
    - name: Run Ruff (format)
      run: ruff format . --check
      continue-on-error: true
